/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-19 03:32:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Chi tiết</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"row bg-title\">\r\n");
      out.write("\t\t<div class=\"col-lg-3 col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("\t\t\t<h4 class=\"page-title\">Chi tiết thành viên</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.row -->\r\n");
      out.write("\t<!-- .row -->\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-4 col-xs-12\">\r\n");
      out.write("\t\t\t<div class=\"white-box\">\r\n");
      out.write("\t\t\t\t<div class=\"user-bg\">\r\n");
      out.write("\t\t\t\t\t<img width=\"100%\" alt=\"user\" src=\"/CrmApp/static/plugins/images/large/img1.jpg\">\r\n");
      out.write("\t\t\t\t\t<div class=\"overlay-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"user-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0)\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"/CrmApp/static/plugins/images/users/genu.jpg\" class=\"thumb-lg img-circle\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"img\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"text-white\">phongpham</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"text-white\">info@myadmin.com</h5>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"user-btm-box\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-sm-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-purple\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ti-facebook\"></i>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>20%</h4>\r\n");
      out.write("\t\t\t\t\t\t<h6>Chưa thực hiện</h6>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-sm-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-blue\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ti-twitter\"></i>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>50%</h4>\r\n");
      out.write("\t\t\t\t\t\t<h6>Đang thực hiện</h6>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-sm-4 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ti-dribbble\"></i>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>30%</h4>\r\n");
      out.write("\t\t\t\t\t\t<h6>Hoàn thành</h6>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-8 col-xs-12\">\r\n");
      out.write("\t\t\t<div class=\"white-box\">\r\n");
      out.write("\t\t\t\t<form class=\"form-horizontal form-material\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-md-12\">Full Name</label>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.fullname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"example-email\" class=\"col-md-12\">Email</label>\r\n");
      out.write("\t\t\t\t\t \t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-md-12\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-md-12\">Phone No</label>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"col-sm-12\">Address</label>\r\n");
      out.write("\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<!-- /.row -->\r\n");
      out.write("\t<!-- BEGIN DANH SÁCH CÔNG VIỆC -->\r\n");
      out.write("\t<h4>DANH SÁCH CÔNG VIỆC</h4>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<div class=\"white-box\">\r\n");
      out.write("\t\t\t\t<h3 class=\"box-title\">Chưa thực hiện</h3>\r\n");
      out.write("\t\t\t\t<div class=\"message-center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mail-contnet\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Pavan kumar</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mail-desc\">Just see the my admin!</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"time\">9:30 AM</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mail-contnet\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Sonu Nigam</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mail-desc\">I've sung a song! See you at</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"time\">9:10 AM</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<div class=\"white-box\">\r\n");
      out.write("\t\t\t\t<h3 class=\"box-title\">Đang thực hiện</h3>\r\n");
      out.write("\t\t\t\t<div class=\"message-center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mail-contnet\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Pavan kumar</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mail-desc\">Just see the my admin!</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"time\">9:30 AM</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mail-contnet\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Sonu Nigam</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mail-desc\">I've sung a song! See you at</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"time\">9:10 AM</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<div class=\"white-box\">\r\n");
      out.write("\t\t\t\t<h3 class=\"box-title\">Đã hoàn thành</h3>\r\n");
      out.write("\t\t\t\t<div class=\"message-center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mail-contnet\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Pavan kumar</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mail-desc\">Just see the my admin!</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"time\">9:30 AM</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mail-contnet\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>Sonu Nigam</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"mail-desc\">I've sung a song! See you at</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"time\">9:10 AM</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END DANH SÁCH CÔNG VIỆC -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
